//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaplingTree.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintance
    {
        public long Id { get; set; }
        public long SaplingId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string Description { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Sapling Sapling { get; set; }
        public virtual User User { get; set; }
    }
}
