//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sapling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sapling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sapling()
        {
            this.Maintance = new HashSet<Maintance>();
            this.Support = new HashSet<Support>();
            this.SaplingImage = new HashSet<SaplingImage>();
        }
    
        public long Id { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Photo { get; set; }
        public bool IsExists { get; set; }
        public Nullable<int> NextActionId { get; set; }
        public string NextActionText { get; set; }
        public string ReasonForNotExists { get; set; }
        public Nullable<int> TreeId { get; set; }
        public string NickName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Action Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintance> Maintance { get; set; }
        public virtual Tree Tree { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Support> Support { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaplingImage> SaplingImage { get; set; }
    }
}
