//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sapling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public long SaplingId { get; set; }
    
        public virtual Sapling Sapling { get; set; }
    }
}
